---
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    number_sections: no
bibliography: Zotero_bibliography.bib
---
# Portfolio
___Auteur:___ Nonne Hodes, 
___Date:___ june 6, 2023

Welkom in mijn portfolio! Hier vind je een verzameling van mijn opdrachten die ik de afgelopen periode heb uitgevoerd. Mijn naam is Nonne Hodes, ik ben een 22 jarige studentte aan Hogeschool Utrecht, onderdeel van de opleiding Biologie en medisch laboratoriumonderzoek. Ik ben enthousiast om jullie wat meer te vertellen over mijn specialisatie, Data schience. Ik ben deze periode gepassioneerd bezig geweest met verschillende taken. Dit portfolio dient als een overzicht van mijn vaardigheden, prestaties en groei als professional.

Binnen dit portfolio kun je een diversiteit aan opdrachten ontdekken met betrekking tot programeren op biologsich gebied. Elk item in mijn portfolio is zorgvuldig samengesteld om een representatieve weergave te bieden van mijn competenties, creativiteit en vermogen om uitdagingen aan te gaan.

Ik nodig je uit om door mijn werk te bladeren en een kijkje te nemen in mijn leergroei. Mocht je vragen hebben of interesse hebben in een specifiek project, aarzel dan niet om contact met me op te nemen. Bedankt voor je bezoek aan mijn portfolio en ik hoop dat mijn werk je inspireert en intrigeert.

Veel plezier met het verkennen van mijn portfolio!

Met vriendelijke groet,

Nonne Hodes

> Contactgegevens:

* E-mailadres: nonne.hodes@student.hu.nl
* LinkedIn-profiel: [Nonne Hodes](https://www.linkedin.com/in/nonne-hodes-00842a15b)
